# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branch: "main"
  schedule：
    - corn：30 */5 * * *

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone miao plugin
        run: git clone https://gitee.com/yoimiya-kokomi/miao-plugin.git ./plugins/miao-plugin/
      - name: install Homebrew
        run: brew install redis
      - name: start redis server
        run: brew services start redis
      - name: test redis
        run: redis-cli
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          with: 'npm'
      - run: npm install pnpm -g
      - run: pnpm install -P
      - run: node app
